href:
  rails_news: https://news.railstutorial.org/
  michael_hartl: https://www.michaelhartl.com/
  rails_tutorial: https://www.railstutorial.org/
  learn_enough: https://www.learnenough.com/
  rails_book: https://www.railstutorial.org/book
  screen_cast: https://screencasts.railstutorial.org/
  contact_page: https://www.railstutorial.org/contact
  rails_help: https://www.railstutorial.org/help
  rails_page: https://rubyonrails.org/
  gavatar: https://gravatar.com/emails
variable_length:
  name: 50
  email: 255
  password: 6
  micropost: 140
size:
  gravatar: 50
  image: 300
  image_size: 5
pagination:
  user_per_page: 30
  micro_per_page: 30
password_reset:
  expired_time: 2
format:
  image: ["image/jpeg", "image/gif", "image/png"]
  accept_image: "image/jpeg,image/gif,image/png"
unit:
  byte: 1024
