href:
  rails_news: https://news.railstutorial.org/
  michael_hartl: https://www.michaelhartl.com/
  rails_tutorial: https://www.railstutorial.org/
  learn_enough: https://www.learnenough.com/
  rails_book: https://www.railstutorial.org/book
  screen_cast: https://screencasts.railstutorial.org/
  contact_page: https://www.railstutorial.org/contact
  rails_help: https://www.railstutorial.org/help
  rails_page: https://rubyonrails.org/
